
name: Train_nips23
model_type: ImageDemoire
num_gpu: auto  # set num_gpu: 0 for cpu mode
find_unused_parameters: False
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: MultiFrameVD
    #### different from V1
    type: NIPS23ImageYCbCrDataset
    dataroot_gt_rgb: /data/rjy/dataset/liujicheng/video_dataset/merge/train/gt_rgb
    dataroot_gt_raw: /data/rjy/dataset/liujicheng/video_dataset/merge/train/gt_raw
    dataroot_lq_rgb: /data/rjy/dataset/liujicheng/video_dataset/merge/train/moire_rgb
    dataroot_lq_raw: /data/rjy/dataset/liujicheng/video_dataset/merge/train/moire_raw
    io_backend:
      type: disk
    gt_size: 256
    crop_size: 256
    height: 1280
    width: 720
    use_hflip: true
    use_rot: false
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~
  val:
    name: MultiFrameVD
    #### different from V1
    type: NIPS23ImageYCbCrDataset
    dataroot_gt_rgb: /data/rjy/dataset/liujicheng/video_dataset/merge/test/gt_rgb
    dataroot_gt_raw: /data/rjy/dataset/liujicheng/video_dataset/merge/test/gt_raw
    dataroot_lq_rgb: /data/rjy/dataset/liujicheng/video_dataset/merge/test/moire_rgb
    dataroot_lq_raw: /data/rjy/dataset/liujicheng/video_dataset/merge/test/moire_raw
    io_backend:
      type: disk
    batch_size: 1
    num_worker: 8
    

# network structures
network_g:
  type: DSDNet
  n_feat: 48
  scale_unetfeats: 24
  Depth: [1, 1, 1]

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [400000]
    gamma: 0.1


  total_iter: 400000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  Y_opt:
    type: L2_Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: VGGPerceptualLoss
    loss_weight: 1.0
    resize: True

  color_opt:
    type: ColorLoss
    loss_weight: 1.
  
# validation settings
val:
  val_freq: !!float 5000
  save_img: false

  metrics:
    psnr:
      type: calculate_psnr_pt
      crop_border: 0
    ssim:
      type: calculate_ssim_pt
      crop_border: 0

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
